### PR TITLE
handle update between different mount points

### LINKED ISSUE #3: Handle different mount points when generating output via update feature
## The problem
Currently, I can't update my `ct` files' outputs.

## The reason
My `/tmp` is mounted at a different mount point than where my `*.ct` files are. Therefore, when updating them (by passing `true` as second argument to `(*TestSuite).Run`), I get the following error:
```sh
rename /tmp/cmdtest196280009 <my-ct-file-at-different-mount-than-tmp>: invalid cross-device link
```

This is due to [using `os.Rename` to do the copy](https://github.com/google/go-cmdtest/blob/2e125d9190f5098e5b772eed02aaf9b199d1a0cb/cmdtest.go#L341), which can't handle different mount points.

This happens because `os.Rename` uses the [`rename` syscall](http://man7.org/linux/man-pages/man2/rename.2.html) under the hood, which, in its manual page, states:
> (...) Linux permits a filesystem to be mounted at multiple points, but `rename()` does not work across different mount points, even if the same filesystem is mounted on both.

## The solution
A possible solution would be to [create, copy and remove the file in separate steps](https://gist.github.com/var23rav/23ae5d0d4d830aff886c3c970b8f6c6b), which will avoid calling the `rename` syscall.

---
Nonetheless, great work so far, thanks!

### PR DESCRIPTION
**Pull request by gbrlsnchs**
This PR fixes #3.

### CODE REVIEW

File: cmdtest.go [hunk 1]
```diff
@@ -691,6 +691,25 @@ func fixedArgBuiltin(nargs int, f func([]string) ([]byte, error)) CommandFunc {
...
+	src, err := os.Open(oldpath)
+	if err != nil {
+		return err
+	}
+	dst, err := os.Create(newpath)
+	if err != nil {
+		return err
+	}
+	defer dst.Close()
+	defer src.Close()
```
Comment (vangent) [inline cmdtest.go]: Nit: this should be moved up before the `os.Create` so that src is closed if `os.Create` fails.

File: cmdtest.go [hunk 2]
```diff
@@ -691,6 +691,25 @@ func fixedArgBuiltin(nargs int, f func([]string) ([]byte, error)) CommandFunc {
...
+	// able to rename files between different mount points.
+	src, err := os.Open(oldpath)
+	if err != nil {
+		return err
+	}
+	dst, err := os.Create(newpath)
+	if err != nil {
+		return err
+	}
+	defer dst.Close()
```
Comment (jba) [inline cmdtest.go]: You can't ignore Close errors on write. Close may cause bytes to be written as part of a final flush.

File: cmdtest.go [hunk 3]
```diff
@@ -691,6 +691,25 @@ func fixedArgBuiltin(nargs int, f func([]string) ([]byte, error)) CommandFunc {
...
+	defer src.Close()
+	if _, err = io.Copy(dst, src); err != nil {
+		return err
```
Comment (jba) [inline cmdtest.go]: We need to let the user know here that things are corrupted: their original file is in an unknown state, but oldpath has the right contents.

(That's why I used the OS rename; it's basically atomic, on Unix at least.)

I would just add info to the error with fmt.Errorf.

**Comment by gbrlsnchs** [comment]
Thanks for the reviews, I'll do the changes soon. :cat:

File: cmdtest.go (hunk 3 above)
Comment (gbrlsnchs) [reply cmdtest.go]: I'm thinking about something like the following:
```go
if n, err := io.Copy(dst, src); err != nil {
	return fmt.Errorf("go-cmdtest: could only copy %d bytes: %v", n, err)
}
```
What do you think, @jba?

Comment (jba) [reply cmdtest.go]: Mention that the destination file may be corrupted, too.

**Comment by gbrlsnchs** [comment]
@vangent and @jba, it seems like this problem could be solved if we used https://github.com/google/renameio in place of my hackish solution.

Under the hood it renames the file atomically (just like it was done before) but in case of failure when calling `os.Rename`, it fallbacks to an alternate route in the same mount point (doesn't matter which, the tmp file gets deleted nonetheless).

If you agree, I could rebase this solution with a working one using renameio or even open a new PR with it. I already adapted the code and all tests are passing.

**Comment by jba** [comment]
That package sounds awesome to me. I'd be happy if you used it.

**Comment by gbrlsnchs** [comment]
@jba @vangent Rebase done, now with the `renameio` solution.

File: cmdtest.go [hunk 4]
```diff
@@ -335,10 +336,11 @@ func (ts *TestSuite) update(t *testing.T) {
 	for _, tf := range ts.files {
 		t.Run(strings.TrimSuffix(tf.filename, ".ct"), func(t *testing.T) {
 			tmpfile, err := tf.updateToTemp()
+			defer tmpfile.Cleanup()
```
Comment (jba) [inline cmdtest.go]: I think this should be moved after the `if err != nil` check. `tmpfile` can be nil if err is not.

Also, check the error from Cleanup and fail it it's not nil.

File: cmdtest_test.go [hunk 5]
```diff
@@ -195,12 +196,33 @@ func TestUpdateToTemp(t *testing.T) {
...
-		defer os.Remove(fname)
-		if diff := diffFiles(t, "testdata/good/good.ct", fname); diff != "" {
+		if diff := diffFiles(t, "testdata/good/good.ct", f.Name()); diff != "" {
+			t.Errorf("%s: %s", dir, diff)
+		}
+	}
+}
+
+func TestUpdate(t *testing.T) {
+	for _, dir := range []string{"update"} {
```
Comment (jba) [inline cmdtest_test.go]: Why a loop if there's only one value?

Comment (gbrlsnchs) [reply cmdtest_test.go]: I did this in order to make adding more tests cases easier. Should I remove the loop?

File: cmdtest.go (hunk 4 above)
Comment (gbrlsnchs) [reply cmdtest.go]: Oops, my bad. I deferred the cleanup before checking `err` because the file also needs to be cleaned up when there is a writing error, not only in successful scenarios.

Therefore, I fixed it and rebased in https://github.com/google/go-cmdtest/pull/4/commits/b1b394ee42be715f4f7eafd5238275efe116b453.

Now when there's a write error, `(*TestSuite).write` returns both the file pointer and the error, so we can defer a cleanup whenever `tmpfile` is not `nil`.

File: cmdtest_test.go (hunk 5 above)
Comment (jba) [reply cmdtest_test.go]: Yes. We can add it back if we need it.

Comment (gbrlsnchs) [reply cmdtest_test.go]: All right, done and rebased in 2305b24.

**Comment by jba** [comment]
Thanks!
